'use strict';

/** @type {Record<string, Record<string, string>>} */
const INFO_STATE_LABELS = {
	connection: {
		en: 'MotionEye reachable',
		de: 'MotionEye erreichbar',
		ru: 'MotionEye доступен',
		pt: 'MotionEye acessível',
		nl: 'MotionEye bereikbaar',
		fr: 'MotionEye accessible',
		it: 'MotionEye raggiungibile',
		es: 'MotionEye accesible',
		pl: 'MotionEye osiągalny',
		uk: 'MotionEye доступний',
		'zh-cn': 'MotionEye 可访问',
	},
	camerasOnline: {
		en: 'Cameras online',
		de: 'Kameras online',
		ru: 'Камер онлайн',
		pt: 'Câmeras online',
		nl: "Camera's online",
		fr: 'Caméras en ligne',
		it: 'Telecamere online',
		es: 'Cámaras en línea',
		pl: 'Kamery online',
		uk: 'Камер онлайн',
		'zh-cn': '在线摄像头数',
	},
	lastSync: {
		en: 'Last MotionEye sync',
		de: 'Letzte MotionEye-Synchronisation',
		ru: 'Последняя синхронизация MotionEye',
		pt: 'Última sincronização MotionEye',
		nl: 'Laatste MotionEye-synchronisatie',
		fr: 'Dernière synchronisation MotionEye',
		it: 'Ultima sincronizzazione MotionEye',
		es: 'Última sincronización MotionEye',
		pl: 'Ostatnia synchronizacja MotionEye',
		uk: 'Остання синхронізація MotionEye',
		'zh-cn': '上次 MotionEye 同步',
	},
	motionEyeVersion: {
		en: 'MotionEye version',
		de: 'MotionEye-Version',
		ru: 'Версия MotionEye',
		pt: 'Versão MotionEye',
		nl: 'MotionEye-versie',
		fr: 'Version MotionEye',
		it: 'Versione MotionEye',
		es: 'Versión MotionEye',
		pl: 'Wersja MotionEye',
		uk: 'Версія MotionEye',
		'zh-cn': 'MotionEye 版本',
	},
	motionVersion: {
		en: 'Motion daemon version',
		de: 'Motion-Daemon-Version',
		ru: 'Версия демона Motion',
		pt: 'Versão do daemon Motion',
		nl: 'Motion-daemonversie',
		fr: 'Version du démon Motion',
		it: 'Versione demone Motion',
		es: 'Versión del demonio Motion',
		pl: 'Wersja demona Motion',
		uk: 'Версія демона Motion',
		'zh-cn': 'Motion 守护进程版本',
	},
};

module.exports = {
	INFO_STATE_LABELS,
};
